version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github_actions"
    commit-message:
      prefix: "build(deps)"
    open-pull-requests-limit: 5
